apiVersion: v1
kind: Namespace
metadata:
  name: lab-red
  labels: { team: lab }
---
apiVersion: v1
kind: Namespace
metadata:
  name: lab-blue
  labels: { team: lab }
---
apiVersion: v1
kind: Namespace
metadata:
  name: lab-tools
  labels: { team: lab }
